export const ATTENDANCE_DATA = {
  attendanceView: 'Attendance view',
  date: 'Date',
  expectedCheckIn: 'Expected check in',
  checkInTime: 'Check in time',
  checkTimeout: 'Check out time',
  expectedCheckOut: 'Expected check out',
  close: 'Close',
  employeeId: 'Employee ID',
  company: 'Company',
  branch: 'Branch',
  jobTitle: 'Job title',
  companyName: 'eSpark talent',
  name: 'Name',
  location: 'Location',
  department: 'Department',
  joiningDate: 'Joining date',
  view: 'View',
};
export const EMPLOYEE_DATA = [
  {
    employeeIdCode: '12222',
    employeeName: 'Bilal Ahmed Khan',
    companyName: 'eSpark talent',
    branchName: 'Jauhar, Block 1',
    jobTitleName: 'Web Developer',
    location: 'Karachi,Pakistna',
    department: 'Software',
    joiningDate: 'Oct26,2021',
  },
  {
    employeeIdCode: '12223',
    employeeName: 'Areeba Shakeel',
    companyName: 'eSpark talent',
    branchName: 'Jauhar, Block 1',
    jobTitleName: 'Ui/Ux Developer',
    location: 'Karachi,Pakistna',
    department: 'Software',
    joiningDate: 'Sept06,2021',
  },
];
